name: iOS CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  build_and_test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app
    
    - name: Install SwiftLint
      run: brew install swiftlint
    
    - name: SwiftLint
      run: swiftlint lint --reporter github-actions-logging
      
    - name: Install Fastlane
      run: brew install fastlane

    - name: Build
      run: |
        xcodebuild clean build \
          -scheme "TacoBellApp" \
          -destination "platform=iOS Simulator,name=iPhone 14"
          
    - name: Build Complete
      run: |
        echo "Build completed successfully"
